var child = [
  { 'dupe': false, 'type': 8, 'name': 'checkForm.js', 'dir': 'c0', 'linked': 2, 'url': 'http://crypto.test/js/checkForm.js', 'fetched': true, 'code': 200, 'len': 3321, 'decl_mime': 'application/x-javascript', 'sniff_mime': 'text/html', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xc5c4f230 },
  { 'dupe': false, 'type': 8, 'name': 'checkInput.js', 'dir': 'c1', 'linked': 2, 'url': 'http://crypto.test/js/checkInput.js', 'fetched': true, 'code': 200, 'len': 1205, 'decl_mime': 'application/x-javascript', 'sniff_mime': 'application/binary', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xce7ab6d7 },
  { 'dupe': false, 'type': 8, 'name': 'checkLinks.js', 'dir': 'c2', 'linked': 2, 'url': 'http://crypto.test/js/checkLinks.js', 'fetched': true, 'code': 200, 'len': 297, 'decl_mime': 'application/x-javascript', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'jquery-3.1.1.min.js', 'dir': 'c3', 'linked': 5, 'url': 'http://crypto.test/js/jquery-3.1.1.min.js', 'fetched': true, 'code': 200, 'len': 86709, 'decl_mime': 'application/x-javascript', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 3, 0, 0, 1, 0 ], 'sig': 0x43e22f5a },
  { 'dupe': false, 'type': 8, 'name': 'r.fx.off||d.hidden', 'dir': 'c4', 'linked': 1, 'url': 'http://crypto.test/js/r.fx.off||d.hidden', 'fetched': true, 'code': 404, 'len': 1194, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x108d2149 },
  { 'dupe': false, 'type': 8, 'name': 'veryBadScript.js', 'dir': 'c5', 'linked': 2, 'url': 'http://crypto.test/js/veryBadScript.js', 'fetched': true, 'code': 200, 'len': 368, 'decl_mime': 'application/x-javascript', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c6', 'linked': 2, 'url': 'http://crypto.test/js/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 1760, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c7', 'linked': 2, 'url': 'http://crypto.test/js/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 1760, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
